// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Puck.Databases;

#nullable disable

namespace Puck.Migrations.BulletinDatabaseMigrations
{
    [DbContext(typeof(BulletinDatabase))]
    partial class BulletinDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Puck.Databases.Bulletin", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AcceptAnyRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DpsIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DpsMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MentionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TankIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TankMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("Bulletins");
                });
#pragma warning restore 612, 618
        }
    }
}
